export enum ROOT_ROUTES {
  BOTTOM_TAB_STACK = 'BOTTOM_TAB_STACK',
  HOME_STACK = 'HOME_STACK',
  AUTH_STACK = 'AUTH_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
  WORKSHEET_STACK = 'WORKSHEET_STACK',
  TAKE_OFF_STACK = 'TAKE_OFF_STACK',
  SERVICE_STACK = 'SERVICE_STACK',
}
export enum BOTTOM_TAB_ROUTES {
  HOME = 'Trang chủ ',
  SEARCH = 'Tìm kiếm',
  ORDER = 'Đơn hàng',
  ACCOUNT = 'Tài khoản',
}
export enum HOME_ROUTES {
  NOTIFICATION = 'NOTIFICATION',
  INFO_NOTIFICATION = 'INFO_NOTIFICATION',
  INFO_NOTIFICATION_DETAIL = 'INFO_NOTIFICATION_DETAIL',
  CONTROL = 'CONTROL',
  HISTORY_DEVICE = 'HISTORY_DEVICE',
  SETTING_DEVICE = 'SETTING_DEVICE',
  LIST_USER = 'LIST_USER',
  ADD_USER = 'ADD_USER'

}
export enum SERVICE_PREPARE_ROUTES {
  SERVICE_PREPARE = 'SERVICE_PREPARE',
  MAP_SERVICE_PREPARE = 'MAP_SERVICE_PREPARE',
DETAIL_SERVICE_PREPPARE = 'DETAIL_SERVICE_PREPPARE',

}
export enum AUTH_ROUTES {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  AUTHEN_CODE = 'AUTHEN_CODE',
  CONFIRM_PASSWORD = 'CONFIRM_PASSWORD',

}

export enum PROFILE_ROUTES {
  ACCOUNT_INFO = 'ACCOUNT_INFO',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  REVENUA_INFO = "REVENUA_INFO",
  FONT_SIZE = 'FONT_SIZE',
  SUPPORT = 'SUPPORT',
  REQUEST_SUPPORT = 'REQUEST_SUPPORT',
  LIST_TECHNICIAN = 'LIST_TECHNICIAN',
  DETAIL_ORDER = "DETAIL_ORDER"
}
